"""V2

Revision ID: e3b0907ad43d
Revises: 
Create Date: 2021-12-06 10:14:55.644923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b0907ad43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altoMax', sa.Float(), nullable=True),
    sa.Column('anchoMax', sa.Float(), nullable=True),
    sa.Column('largoMax', sa.Float(), nullable=True),
    sa.Column('pesoMax', sa.Float(), nullable=True),
    sa.Column('id_hub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_hub'], ['hub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dron')
    # ### end Alembic commands ###
